const actionTypes = {
	'APP_INIT': 'APP_INIT',
	'USER_INIT': 'USER_INIT',
	'USER_LOADING': 'USER_LOADING',
	'USER_LOGOUT': 'USER_LOGOUT',
	'USER_DATA': 'USER_DATA',
	'MEET_CONNECT': 'MEET_CONNECT',
	'MEET_LINE': 'MEET_LINE',
	'MEET_DOCS': 'MEET_DOCS',
	'MEET_CREATE': 'MEET_CREATE',
	'DOC_LOADING': 'DOC_LOADING',
	'DOC_LIST': 'DOC_LIST',
}

export default actionTypes
